# Screen and Camera settings
WEBCAM_WIDTH = 640
WEBCAM_HEIGHT = 480
PROCESSING_WIDTH = 320
PROCESSING_HEIGHT = 240

# --- Mouse Control Settings ---
SENSITIVITY = 1.2
DRAG_SENSITIVITY = 0.7
SCROLL_SENSITIVITY = 50
DEADZONE_THRESHOLD = 1.0
ACCELERATION_FACTOR = 0.03

# --- Kalman Filter Tuning ---
KF_MEASUREMENT_NOISE = 0.6
KF_PROCESS_NOISE = 0.01

# --- Gesture Settings ---
PINCH_THRESHOLD = 0.06
POINTING_THRESHOLD = 0.07
FIST_THRESHOLD = 0.15
CLICK_GESTURE = "Thumb_Up"
NEUTRAL_GESTURE = "Victory"
