[project]
name = "CameraCursor"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "mediapipe>=0.10.14",
    "opencv-python>=4.12.0.88",
    "pyautogui>=0.9.54",
]
